language: php

php:
  - 5.6

services:
  - redis-server

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction -o
  - ls -alh
  - cp tests/config.php config/config.php
  - cat config/config.php
  - cp tests/phinx.yml .
  - cat phinx.yml
  - phpenv config-add tests/phpsettings.ini
  - php vendor/bin/phinx migrate
  - php vendor/bin/phinx status

script:
  - phpunit --coverage-clover=coverage.clover --bootstrap tests/init.php tests/*
  - php tests/coverage-checker.php coverage.clover 75

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
